### ISSUE TITLE
Update page status via web interface

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-mc#5]
This should be possible from all different loacations in the TWI to allow the crowd user to notify the collection owner that he is 'Done' with this page as well as let the owner set the status to 'Final' if transcript is correct or reset to 'InProgress' if quality is not sufficient.
Rest service is already available.

**Comment by hackmanschorsch** [comment]
For the edit interface: set page status to Done, Final or Ground Truth with a check box
First I will create the rest call for this.

**Comment by kahlep** [comment]
The existing API call for updating the status is the following:
POST /collections/{collId}/{docId}/{pageNr}/{transcriptId}

Query Parameters:
"status": NEW | IN_PROGRESS | DONE | FINAL | GT
"note": optional commit message string

If the user, making this call, is the one who stored the transcript then the status of that is just updated.
If another user updates the status, then a new version of the transcript is created in order to capture this activity.

**Comment by hackmanschorsch** [comment]
use case changed slightly - see new issue TWI-edit/#58 This is closed therefor
