### ISSUE TITLE
User guide for crowd-source project creation

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-mc#9]
To give details of the steps required in the expert tool to prepare a collection for crowd sourcing

**Comment by cziaarm** [comment]
https://transkribus.eu/readTest/crowd/

**Comment by EvaMLang** [comment]
Who originally wrote the instructions? @jupouta ?

I would suggest setting up a HowTo document for crowdsourcing - following the style of the project HowTo guides (cf. https://transkribus.eu/wiki/index.php/How_to_Guides). Templates avaiable here: https://read02.uibk.ac.at/wiki/index.php/Resources

**Comment by maxbry** [comment]
The user guide has been created, so being picky, this issue would have to be closed. What about Eva's remark of the howto guide in the typical Transkribus style?

**Comment by EvaMLang** [comment]
I tried to follow the steps as indicated in the write-up - unfortunately, they are not clear enough. Rough summary:

- screenshots are misleading / not clear enough
- backend functionality is not (yet?) working:
   - milestone due date is off by one month (in the past!??!!) when selected from the data chooser dialog
   - dialog for marking a collection as crowdsourcing informs the user about opening the collection to the general public but does not allow applying this flag
   - Landing web page for crowdsourcing states in GUI: http://transkribus.eu/crowd/<colID> (which is not yet set up so cannot be tested)

** Add manuscripts**
Further references on how to do this are required (see e.g. 10-steps-HowTo guide on creating documents/collections/adding existing documents to new collections etc.). Screenshot misleading.

** Line segmentation**
Further references on how to do this are required (see e.g. HowTo guide on Segmentation)

** Polygon2Baseline tool**
Screenshot does not show the usere on where exactly the tool can be found --> replace

** Mark as crowdsourcing**
Would be nice if it worked (see general comments above). 
It is also not clear where the modification dialog for collections could be found (click on collection name in tab "Server", choose the collection name and click the "modify" button).

** Choose a representative image**
Nice, but how could I do this?

** Run HTR**
Better call this "automatically process segmented documents" or something along those lines. Would rather expect a clear reference to HowTo guides here instead of screenshots which will not help me much, sorry.

** Define a tag set**
Nice to have - however AFAIK this is on document level, not on collection level (which is not stated clear enough)

**Comment by EvaMLang** [comment]
Just opened bug in TranskribusSwtGUI: https://github.com/Transkribus/TranskribusSwtGui/issues/129
